LanchesMac/LanchesMac/Models/CarrinhoCompra.cs
using LanchesMac.Data;
using Microsoft.EntityFrameworkCore;

namespace LanchesMac.Models
{
    public class CarrinhoCompra
    {
        private readonly AppDbContext _context;

        public string CarrinhoDeCompraId { get; set; }
        public List<CarrinhoCompraItem> CarrinhoCompraItems { get; set; }

        public CarrinhoCompra(AppDbContext context)
        {
            _context = context;
        }

        public static CarrinhoCompra GetCarrinho(IServiceProvider services)
        {
            ISession session = 
                services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<AppDbContext>();

            string carrinhoId = session.GetString("CarrinhoId") ?? Guid.NewGuid().ToString();

            session.SetString("CarrinhoId", carrinhoId);

            return new CarrinhoCompra(context)
            {
                CarrinhoDeCompraId = carrinhoId,
            };
        }
        public void AdicionarAoCarrinho(Lanche lanche)
        {
            var carrinhoCompraItem = _context.carrinhoCompraItens
                .SingleOrDefault(s => s.Lanche.LancheId == lanche.LancheId &&
                s.CarrinhoDeCompraId == CarrinhoDeCompraId);

            if(carrinhoCompraItem != null)
            {
                carrinhoCompraItem.Quantidade++;
                _context.SaveChanges();
                return;
            }

            carrinhoCompraItem = new CarrinhoCompraItem()
            {
                CarrinhoDeCompraId = CarrinhoDeCompraId,
                Quantidade = 1,
                Lanche = lanche,
            };
            _context.carrinhoCompraItens.Add(carrinhoCompraItem);
            _context.SaveChanges();
        }
        public int RemoverDoCarrinho(Lanche lanche)
        {
            var carrinhoCompraItem = _context.carrinhoCompraItens
                .SingleOrDefault(s => s.Lanche.LancheId == lanche.LancheId &&
                s.CarrinhoDeCompraId == CarrinhoDeCompraId);

            var quantidadeLocal = 0;

            if(carrinhoCompraItem != null)
            {
                if(carrinhoCompraItem.Quantidade <= 1)
                {
                    _context.Remove(carrinhoCompraItem);
                    _context.SaveChanges();
                    return quantidadeLocal;
                }

                carrinhoCompraItem.Quantidade--;
                quantidadeLocal = carrinhoCompraItem.Quantidade;

            }
            _context.SaveChanges();
            return quantidadeLocal;
        }

        public List<CarrinhoCompraItem> GetCarrinhoCompraItems()
        {
            return CarrinhoCompraItems ?? _context.carrinhoCompraItens
                .Where(c => c.CarrinhoDeCompraId == CarrinhoDeCompraId)
                .Include(s => s.Lanche)
                .ToList();
        }

        public void LimparCarrinho()
        {
            var carrinhoItens = _context.carrinhoCompraItens
                .Where(c => c.CarrinhoDeCompraId == CarrinhoDeCompraId);
            _context.carrinhoCompraItens.RemoveRange(carrinhoItens);
            _context.SaveChanges();
        }

        public decimal GetCarrinhoCompraTotal()
        {
            var total = _context.carrinhoCompraItens
                .Where(c => c.CarrinhoDeCompraId == CarrinhoDeCompraId)
                .Select(c => c.Lanche.Preco * c.Quantidade)
                .Sum();
            return total;
        }
    }
}

LanchesMac/LanchesMac/ViewModels/CarrinhoCompraViewModel.cs
using LanchesMac.Models;

namespace LanchesMac.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra  CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }
    }
}

LanchesMac/LanchesMac/Controllers/CarrinhoCompraController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItems();
            _carrinhoCompra.CarrinhoCompraItems = itens;
            var CarrinhoCompraViewModel = new CarrinhoCompraViewModel()
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(CarrinhoCompraViewModel);
        }

        public RedirectToActionResult AdicionarNoCarrinhoCompra(int idLanche)
        {
            var lancheSelecionado = _lancheRepository.Lanches
                .FirstOrDefault(l => l.LancheId == idLanche);

            if (lancheSelecionado != null) _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult RemoverDoCarrinho(int idLanche)
        {
            var lancheSelecionado = _lancheRepository.Lanches
                .FirstOrDefault(l => l.LancheId == idLanche);

            if (lancheSelecionado != null) _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);

            return RedirectToAction(nameof(Index));
        }
    }
}

LanchesMac/LanchesMac/Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List()
        {
            //var lanches = _lancheRepository.Lanches;
            ViewData["Titulo"] = "Todos os Lanches";
            ViewData["Data"] = DateTime.Now;

            

            //return View(_lancheRepository.Lanches);
            var lanchesViewModel = new LanchesListViewModel();
            lanchesViewModel.Lanches = _lancheRepository.Lanches;
            lanchesViewModel.CategoriaAtual = "Categoria Atual";
            var lanchesTotal = lanchesViewModel.Lanches.Count();
            ViewBag.Lanches = "O Total de Lanches é " + lanchesTotal;
            return View(lanchesViewModel);
        }
    }
}

LanchesMac/LanchesMac/Views/CarrinhoCompra/Index.cshtml
@model CarrinhoCompraViewModel


<div class="container">
    <div class="row">
        <img src="~/assets/img/Full-Cart-icon.png"/>

        <div>
            <h4>Carrinho de Compras: </h4>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Quantidade</th>
                    <th>Lanche</th>
                    <th class="text-right">Preço</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.CarrinhoCompra.CarrinhoCompraItems)
                {
                    <tr>
                        <td class="text-center">@item.Quantidade</td>
                        <td class="text-left">@item.Lanche.Nome</td>
                        <td class="text-right">@item.Lanche.Preco.ToString("C")</td>
                        <td class="text-right">@((item.Lanche.Preco * item.Quantidade).ToString("C"))</td>
                        <td class="text-center">
                            <a asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinhoCompra"
                            asp-route-LancheId = "@item.Lanche.LancheId"
                            >
                            <img src="~/assets/img/remove.png"/>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">
                        Total: 
                    </td>
                    <td class="text-right">
                        @Model.CarrinhoCompraTotal.ToString("C")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
                &ensp;&ensp;&ensp;
                <a class="btn btn-primary" asp-controller="Lanche" asp-action="List">Continuar Comprando</a>
                <br/>
            </div>
        </div>
    </div>
</div>